version: '3.1'
services:
  statistic:
    build: ./statistic
    container_name: statistic
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/stat-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  server:
    build: ./main-service
    container_name: server
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - STAT_URL=http://statistic:9090


  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewm-db
    restart: always
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stat-db:
    image: postgres:13.7-alpine
    container_name: stat-db
    restart: always
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stat-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
